name: "Build and publish image"

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  run:
    name: "Publish image to GitHub Container Registry"
    permissions:
      packages: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=dweb-proxy-api
            org.opencontainers.image.description=eth.limo dWeb Proxy API
            org.opencontainers.image.url=https://github.com/ethlimo/dweb-proxy-api
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and publish container image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
